{{- if .Values.postgresql.enabled }}
{{- $postgresqlSecretName := printf "%s-postgresql" .Release.Name -}}
{{- $postgresqlSecret := (lookup "v1" "Secret" .Release.Namespace $postgresqlSecretName) -}}
{{- if not $postgresqlSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-postgresql" .Release.Name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  # Remove the keep annotation to allow Helm to delete this
  # annotations:
  #   "helm.sh/resource-policy": keep
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  {{ include "credential-showcase.database.adminPasswordKey" . }}: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (printf "%s-postgresql" .Release.Name) "Key" (include "credential-showcase.database.adminPasswordKey" .) "Length" 16) }}
  {{ include "credential-showcase.database.userPasswordKey" . }}: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (printf "%s-postgresql" .Release.Name) "Key" (include "credential-showcase.database.userPasswordKey" .) "Length" 16) }}
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
{{- end }}
{{- end }} 