{{- if .Values.api_server.enabled -}}
{{- if .Values.api_server.openshift.route.enabled -}}
{{- $fullName := printf "%s-%s" .Release.Name .Values.api_server.name -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.api_server.openshift.route.timeout }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ .Values.api_server.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  host: {{ include "credential-showcase.api-server.host" . | quote }}
  path: {{ .Values.api_server.openshift.route.path }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: {{ .Values.api_server.openshift.route.targetPort }}
  wildcardPolicy: {{ .Values.api_server.openshift.route.wildcardPolicy }}
{{ include "credential-showcase.api-server.openshift.route.tls" . | indent 2}}
{{- end }}
{{- end }}

{{- if .Values.traction_adapter.enabled -}}
{{- if .Values.traction_adapter.openshift.route.enabled -}}
{{- $fullName := printf "%s-%s" .Release.Name .Values.traction_adapter.name -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: {{ .Values.traction_adapter.openshift.route.timeout }}
  labels:
    app: {{ $fullName }}
    app.kubernetes.io/name: {{ .Values.traction_adapter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  host: {{ include "credential-showcase.traction-adapter.host" . | quote }}
  path: {{ .Values.traction_adapter.openshift.route.path }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: {{ .Values.traction_adapter.openshift.route.targetPort }}
  wildcardPolicy: {{ .Values.traction_adapter.openshift.route.wildcardPolicy }}
{{ include "credential-showcase.traction-adapter.openshift.route.tls" . | indent 2}}
{{- end }}
{{- end }} 