{{- if .Values.api_server.enabled }}
{{- if .Values.api_server.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-{{ .Values.api_server.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
spec:
  host: pr-{{ .Release.Name }}-{{ .Values.api_server.name }}-dev.apps.silver.devops.gov.bc.ca
  path: {{ .Values.api_server.openshift.route.path }}
  port:
    targetPort: {{ .Values.api_server.openshift.route.targetPort }}
  tls:
    {{- toYaml .Values.api_server.openshift.route.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ .Release.Name }}-{{ .Values.api_server.name }}
  wildcardPolicy: {{ .Values.api_server.openshift.route.wildcardPolicy }}
{{- end }}
---
{{- end }}
{{- if .Values.traction_adapter.enabled }}
{{- if .Values.traction_adapter.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
spec:
  host: pr-{{ .Release.Name }}-{{ .Values.traction_adapter.name }}-dev.apps.silver.devops.gov.bc.ca
  path: {{ .Values.traction_adapter.openshift.route.path }}
  port:
    targetPort: {{ .Values.traction_adapter.openshift.route.targetPort }}
  tls:
    {{- toYaml .Values.traction_adapter.openshift.route.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  wildcardPolicy: {{ .Values.traction_adapter.openshift.route.wildcardPolicy }}
{{- end }}
{{- end }} 