{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credential-showcase.fullname" . }}-postgresql
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
  password: {{ include "postgresql.password" . }}
  postgres-password: {{ include "postgresql.adminPassword" . }}
  replication-password: {{ include "postgresql.password" . }}
---
{{- end }}
{{- if not .Values.rabbitmq.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credential-showcase.fullname" . }}-rabbitmq
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
  password: {{ include "rabbitmq.password" . }}
{{- end }} 