{{- $postgresSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" .Release.Name)) }}
{{- if not $postgresSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  postgres-password: {{ include "postgresql.adminPassword" . }}
  password: {{ include "postgresql.password" . }}
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
---
{{- end }}
{{- $rabbitSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-rabbitmq" .Release.Name)) }}
{{- if not $rabbitSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
type: Opaque
data:
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc }}
  rabbitmq-password: {{ include "rabbitmq.password" . }}
  rabbitmq-username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
  password: {{ include "rabbitmq.password" . }}
  username: {{ .Values.rabbitmq.auth.username | default "guest" | b64enc }}
{{- end }} 