CREATE INDEX "idx_credential_attributes" ON "credentialAttribute" USING btree ("credential_schema");--> statement-breakpoint
CREATE INDEX "idx_icon" ON "credentialDefinition" USING btree ("icon");--> statement-breakpoint
CREATE INDEX "idx_credentialSchema" ON "credentialDefinition" USING btree ("credential_schema");--> statement-breakpoint
CREATE INDEX "idx_credential_representations" ON "credentialRepresentation" USING btree ("credential_definition");--> statement-breakpoint
CREATE INDEX "idx_relyingParty" ON "relyingPartiesToCredentialDefinitions" USING btree ("relying_party");--> statement-breakpoint
CREATE INDEX "idx_logo" ON "relyingParty" USING btree ("logo");--> statement-breakpoint
CREATE INDEX "idx_issuer_logo" ON "issuer" USING btree ("logo");--> statement-breakpoint
CREATE INDEX "idx_issuer" ON "issuersToCredentialDefinitions" USING btree ("issuer");--> statement-breakpoint
CREATE INDEX "idx_issuer_schemas" ON "issuersToCredentialSchemas" USING btree ("issuer");--> statement-breakpoint
CREATE INDEX "idx_scenarios_steps" ON "step" USING btree ("scenario");--> statement-breakpoint
CREATE INDEX "idx_asset_steps" ON "step" USING btree ("asset");--> statement-breakpoint
CREATE INDEX "idx_step_actions" ON "stepAction" USING btree ("step");--> statement-breakpoint
CREATE INDEX "idx_relyingParty_issuer_scenario" ON "scenario" USING btree ("relying_party");--> statement-breakpoint
CREATE INDEX "idx_issuer_scenario" ON "scenario" USING btree ("issuer");--> statement-breakpoint
CREATE INDEX "idx_bannerImage_issuer_scenario" ON "scenario" USING btree ("banner_image");--> statement-breakpoint
CREATE INDEX "idx_revocation_info" ON "revocationInfo" USING btree ("credential_definition");--> statement-breakpoint
CREATE INDEX "idx_headshotImage" ON "persona" USING btree ("headshot_image");--> statement-breakpoint
CREATE INDEX "idx_bodyImage" ON "persona" USING btree ("body_image");--> statement-breakpoint
CREATE INDEX "idx_scenario" ON "scenariosToPersonas" USING btree ("scenario");--> statement-breakpoint
CREATE INDEX "idx_bannerImage" ON "showcase" USING btree ("banner_image");--> statement-breakpoint
CREATE INDEX "showcases_to_credential_definitions_showcase_idx" ON "showcasesToCredentialDefinitions" USING btree ("showcase");--> statement-breakpoint
CREATE INDEX "showcases_to_personas_showcase_idx" ON "showcasesToPersonas" USING btree ("showcase");--> statement-breakpoint
CREATE INDEX "showcases_to_scenarios_showcase_idx" ON "showcasesToScenarios" USING btree ("showcase");