name: Credential Showcase Traction Adapter CI

on:
  push:
    branches:
      - main
      - SHOWCASE-90-pipeline-to-build-and-push
    paths:
      - 'packages/credential-showcase-traction-adapter/**'
      - '.github/workflows/credential-showcase-traction-adapter.yml'
      - '.github/workflows/ci-template.yml'
      - '.github/actions/trivy-scan/**'

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      package_name: credential-showcase-traction-adapter
      docker_image: credential-showcase-traction-adapter
    #   sonar_project_key: credential-showcase-traction-adapter
    # secrets:
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 