name: Uninstall PR resources
on:
  # Add manual trigger with PR number input
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to uninstall'
        required: true
        type: string
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "apps/credential-showcase-api-server/**"
      - "packages/credential-showcase-traction-adapter/**"
      - "docker/dev/**"
      - "charts/**"
    types:
      - closed

jobs:
  uninstall:
    name: Uninstall PR
    environment: development
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'bcgov'
    steps:
      # Set PR number based on event type
      - name: Set PR number
        id: pr_number
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "PR_NUM=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            echo "PR_NUM=${{ github.event.number }}" >> $GITHUB_ENV
          fi

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Uninstall Credential Showcase resources via Helm
        continue-on-error: true
        run: |
          helm uninstall pr-${{ env.PR_NUM }}-credential-showcase

      - name: Remove Credential Showcase Openshift Objects
        continue-on-error: true
        run: |
          oc delete secret,pvc,route,service,deployment,statefulset,configmap \
            --selector "app.kubernetes.io/instance=pr-${{ env.PR_NUM }}-credential-showcase"

  clean-ghcr:
    runs-on: ubuntu-22.04
    name: Delete closed PR images
    steps:
      - name: Delete API Server Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: credential-showcase-api-server
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Delete Traction Adapter Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: credential-showcase-traction-adapter
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.GITHUB_TOKEN }}
